name = "Test Pack"
author = "WinterNode"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff18d5cfdb0cbb95cda150a7b6ec3fb12a7081b9168b5e15291abdfb44c1b010"

[versions]
fabric = "0.15.3"
minecraft = "1.20.2"
